#pragma once

#include <unordered_map>
#include "../common/PixelImage.cpp"


std::unordered_map<char, PixelImage> LETTERS{
    {
        'A',
        {
            {sf::Color::White, {0, 9}},
            {sf::Color::White, {0, 8}},
            {sf::Color::White, {0, 7}},
            {sf::Color::White, {0, 6}},
            {sf::Color::White, {0, 5}},
            {sf::Color::White, {0, 4}},
            {sf::Color::White, {0, 3}},
            {sf::Color::White, {0, 2}},
            {sf::Color::White, {1, 9}},
            {sf::Color::White, {1, 8}},
            {sf::Color::White, {1, 7}},
            {sf::Color::White, {1, 6}},
            {sf::Color::White, {1, 5}},
            {sf::Color::White, {1, 4}},
            {sf::Color::White, {1, 3}},
            {sf::Color::White, {1, 2}},
            {sf::Color::White, {6, 9}},
            {sf::Color::White, {6, 8}},
            {sf::Color::White, {6, 7}},
            {sf::Color::White, {6, 6}},
            {sf::Color::White, {6, 5}},
            {sf::Color::White, {6, 4}},
            {sf::Color::White, {6, 3}},
            {sf::Color::White, {6, 2}},
            {sf::Color::White, {7, 9}},
            {sf::Color::White, {7, 8}},
            {sf::Color::White, {7, 7}},
            {sf::Color::White, {7, 6}},
            {sf::Color::White, {7, 5}},
            {sf::Color::White, {7, 4}},
            {sf::Color::White, {7, 3}},
            {sf::Color::White, {7, 2}},
            {sf::Color::White, {1, 1}},
            {sf::Color::White, {2, 0}},
            {sf::Color::White, {2, 1}},
            {sf::Color::White, {2, 2}},
            {sf::Color::White, {6, 1}},
            {sf::Color::White, {5, 0}},
            {sf::Color::White, {5, 1}},
            {sf::Color::White, {5, 2}},
            {sf::Color::White, {4, 1}},
            {sf::Color::White, {3, 1}},
            {sf::Color::White, {4, 0}},
            {sf::Color::White, {3, 0}},
            {sf::Color::White, {2, 5}},
            {sf::Color::White, {3, 5}},
            {sf::Color::White, {4, 5}},
            {sf::Color::White, {5, 5}},
            {sf::Color::White, {2, 6}},
            {sf::Color::White, {3, 6}},
            {sf::Color::White, {4, 6}},
            {sf::Color::White, {5, 6}},
        }
    }
};
